---
all:
  children:
    home_office:
      children:
        routers:
          hosts:
            core_router01:
              ansible_host: 192.168.1.150
              ansible_network_os: cisco.ios.ios
            core_router02:
              ansible_host: 192.168.1.151
              ansible_network_os: cisco.ios.ios

